### PR TITLE
HOPSWORKS-108

### PR DESCRIPTION
**Pull request by berthoug**
overwrite hadoop-metrics configuration file to write metrics to influxDB
https://hopshadoop.atlassian.net/browse/HOPSWORKS-108

Alternative to hopshadoop/hops-hadoop-chef#38 (merge only one of them)

### CODE REVIEW

**Comment by berthoug** [comment]
This will work only if telegraf is installed on all the node running hadoop (namenode, datanode, resourcemanager, etc.)

**Comment by berthoug** [comment]
@jimdowling, it does not show any part of the code when I click on view changes for your change request. 
Are you asking that I remove the following part?
`owner node.hops.hdfs.user`
`group node.hops.group`

I fail to see why this would be better.

**Comment by jimdowling** [comment]
Sorry, for some reason my in-line comment didn't appear. It's the review system - confuses me :)

The comment was. Change this: #{node.hops.home} to #{node.hops.base_dir}
#{node.hops.home} is the versioned directory, while 'base_dir' is the symbolic link. We should always depend on the 'base_dir' attribute, not the versioned directory.

**Comment by berthoug** [comment]
Ok, good to know, I did the change.

**Pull request merged**
